/*
 * FeedFlow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

//NewPageContent model
type NewPageContent struct {
	Base

	Title   string `json:"title"`
	Content string `json:"content"`
	Tags    []Tag  `json:"tags" gorm:"auto_preload"`
}

//Tag model
type Tag struct {
	BaseNoJSON

	Value            string `json:"value"`
	NewPageContentID uint64 `json:"-"`
}

//ValidNewPageContent - checks limits for a new page content
func ValidNewPageContent(pagecontent *NewPageContent) bool {
	size := len(pagecontent.Title)
	if size < 3 || size > 255 {
		return false
	}

	size = len(pagecontent.Content)
	if size < 2 || size > 20000 {
		return false
	}

	if len(pagecontent.Tags) > 20 {
		return false
	}

	return true
}
