/*
 * FeedFlow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"os"
)

//UploadImg model
type UploadImg struct {
	Hash     string    `json:"hash"`
	FileName **os.File `json:"fileName"`
}
