/*
 * FeedFlow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Add - Add a new page.
func Add(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ImgUpload - Upload a new image.
func ImgUpload(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// Login - Logs in and returns the authentication cookie.
func Login(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// Remove - Move page to archive.
func Remove(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// Signin - Singns in.
func Signin(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
