/*
 * FeedFlow
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// RequestChunk - Return next feed data chunk.
func RequestChunk(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
